name: reddit_clone
description: A Social Media application with Flutter as frontend framework and Firebase as Backend!
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/google.png
    - assets/images/loginEmote.png
    - assets/images/logo.png
