// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxgGI519NBOKXq8SADTsSsoTKZPwqyRoM',
    appId: '1:654620540545:web:61aa6bed632a4a77bd9780',
    messagingSenderId: '654620540545',
    projectId: 'reddit-clone-aa3c6',
    authDomain: 'reddit-clone-aa3c6.firebaseapp.com',
    storageBucket: 'reddit-clone-aa3c6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZLzqDiYYLorthJa3DUOvA9-61hMzdz0c',
    appId: '1:654620540545:android:fd3a382cf6b09e43bd9780',
    messagingSenderId: '654620540545',
    projectId: 'reddit-clone-aa3c6',
    storageBucket: 'reddit-clone-aa3c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDelHCmCp8r8TaftNuPbqg76_yBr0br9xU',
    appId: '1:654620540545:ios:03fdd938270b82b8bd9780',
    messagingSenderId: '654620540545',
    projectId: 'reddit-clone-aa3c6',
    storageBucket: 'reddit-clone-aa3c6.appspot.com',
    iosClientId: '654620540545-isj8lsfvbr0j4kieh1dc8kp2c852de1e.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
